device: cpu
train:
  batch_size: 256
  lr: 0.001
  train_timesteps: 100000
  val_timesteps: 1000
  target_update_timesteps: 1000
  target_update_ratio: 0.005
  discount_factor: 0.99
  replay_buffer_size: 5000
  train_starts_timesteps : 1000
  video_path: ./video
  model_path: ./pretrained
  progress_path: ./train_progress
env:
  env_name: CartPole-v1
  state_dim: 4
  action_dim: 2
model:
  hidden_dim: 128